server:
 port: 8085
 
security:
 jwt:
  public-key: classpath:keystorepublic.txt
spring:
 application:
    name: api-gateway
 cloud:
    gateway:
      routes:
        - id: api-authentication
          uri: "http://localhost:8083"
          predicates: Path=/oauth/**
          filters:
            - RewritePath=/oauth(?<segment>/?.*), $\{segment}
            - RemoveRequestHeader=Cookie
        - id: customer-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - RemoveRequestHeader=Cookie

api:
  sendreport:
    uri: www.repor.com.br
  version: 2.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG